// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: common/proto/adventservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdventService_SolvePart1_FullMethodName = "/adventservice.AdventService/SolvePart1"
	AdventService_SolvePart2_FullMethodName = "/adventservice.AdventService/SolvePart2"
)

// AdventServiceClient is the client API for AdventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdventServiceClient interface {
	SolvePart1(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*InputResponse, error)
	SolvePart2(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*InputResponse, error)
}

type adventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdventServiceClient(cc grpc.ClientConnInterface) AdventServiceClient {
	return &adventServiceClient{cc}
}

func (c *adventServiceClient) SolvePart1(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*InputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InputResponse)
	err := c.cc.Invoke(ctx, AdventService_SolvePart1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventServiceClient) SolvePart2(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*InputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InputResponse)
	err := c.cc.Invoke(ctx, AdventService_SolvePart2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdventServiceServer is the server API for AdventService service.
// All implementations must embed UnimplementedAdventServiceServer
// for forward compatibility.
type AdventServiceServer interface {
	SolvePart1(context.Context, *InputData) (*InputResponse, error)
	SolvePart2(context.Context, *InputData) (*InputResponse, error)
	mustEmbedUnimplementedAdventServiceServer()
}

// UnimplementedAdventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdventServiceServer struct{}

func (UnimplementedAdventServiceServer) SolvePart1(context.Context, *InputData) (*InputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolvePart1 not implemented")
}
func (UnimplementedAdventServiceServer) SolvePart2(context.Context, *InputData) (*InputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolvePart2 not implemented")
}
func (UnimplementedAdventServiceServer) mustEmbedUnimplementedAdventServiceServer() {}
func (UnimplementedAdventServiceServer) testEmbeddedByValue()                       {}

// UnsafeAdventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdventServiceServer will
// result in compilation errors.
type UnsafeAdventServiceServer interface {
	mustEmbedUnimplementedAdventServiceServer()
}

func RegisterAdventServiceServer(s grpc.ServiceRegistrar, srv AdventServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdventService_ServiceDesc, srv)
}

func _AdventService_SolvePart1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).SolvePart1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdventService_SolvePart1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).SolvePart1(ctx, req.(*InputData))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventService_SolvePart2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).SolvePart2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdventService_SolvePart2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).SolvePart2(ctx, req.(*InputData))
	}
	return interceptor(ctx, in, info, handler)
}

// AdventService_ServiceDesc is the grpc.ServiceDesc for AdventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adventservice.AdventService",
	HandlerType: (*AdventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolvePart1",
			Handler:    _AdventService_SolvePart1_Handler,
		},
		{
			MethodName: "SolvePart2",
			Handler:    _AdventService_SolvePart2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/adventservice.proto",
}
