// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: common/proto/adventservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *InputData) Reset() {
	*x = InputData{}
	mi := &file_common_proto_adventservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputData) ProtoMessage() {}

func (x *InputData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_adventservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputData.ProtoReflect.Descriptor instead.
func (*InputData) Descriptor() ([]byte, []int) {
	return file_common_proto_adventservice_proto_rawDescGZIP(), []int{0}
}

func (x *InputData) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type InputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *InputResponse) Reset() {
	*x = InputResponse{}
	mi := &file_common_proto_adventservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputResponse) ProtoMessage() {}

func (x *InputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_adventservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputResponse.ProtoReflect.Descriptor instead.
func (*InputResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_adventservice_proto_rawDescGZIP(), []int{1}
}

func (x *InputResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_common_proto_adventservice_proto protoreflect.FileDescriptor

var file_common_proto_adventservice_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x64, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x21, 0x0a, 0x09, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x9b, 0x01,
	0x0a, 0x0d, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x44, 0x0a, 0x0a, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x31, 0x12, 0x18, 0x2e,
	0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1c, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0a, 0x53, 0x6f, 0x6c, 0x76, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x32, 0x12, 0x18, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x1c, 0x2e,
	0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x61, 0x6c, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x66, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0x30, 0x32, 0x34, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_adventservice_proto_rawDescOnce sync.Once
	file_common_proto_adventservice_proto_rawDescData = file_common_proto_adventservice_proto_rawDesc
)

func file_common_proto_adventservice_proto_rawDescGZIP() []byte {
	file_common_proto_adventservice_proto_rawDescOnce.Do(func() {
		file_common_proto_adventservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_adventservice_proto_rawDescData)
	})
	return file_common_proto_adventservice_proto_rawDescData
}

var file_common_proto_adventservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_adventservice_proto_goTypes = []any{
	(*InputData)(nil),     // 0: adventservice.InputData
	(*InputResponse)(nil), // 1: adventservice.InputResponse
}
var file_common_proto_adventservice_proto_depIdxs = []int32{
	0, // 0: adventservice.AdventService.SolvePart1:input_type -> adventservice.InputData
	0, // 1: adventservice.AdventService.SolvePart2:input_type -> adventservice.InputData
	1, // 2: adventservice.AdventService.SolvePart1:output_type -> adventservice.InputResponse
	1, // 3: adventservice.AdventService.SolvePart2:output_type -> adventservice.InputResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_adventservice_proto_init() }
func file_common_proto_adventservice_proto_init() {
	if File_common_proto_adventservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_adventservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_adventservice_proto_goTypes,
		DependencyIndexes: file_common_proto_adventservice_proto_depIdxs,
		MessageInfos:      file_common_proto_adventservice_proto_msgTypes,
	}.Build()
	File_common_proto_adventservice_proto = out.File
	file_common_proto_adventservice_proto_rawDesc = nil
	file_common_proto_adventservice_proto_goTypes = nil
	file_common_proto_adventservice_proto_depIdxs = nil
}
