hostname: 'aoc2024.se'
cert:
  crtFile: 'certs/aoc2024.crt'
  keyFile: 'certs/aoc2024.key'

days:
  - day: '01'
    replicas: 2
    version: v1
    # These parameters are optional,
    # set here with default values as an example.
    containerHttpPort: 3000
    serviceHttpPort: 3000
    containerGrpcPort: 50051
    serviceGrpcPort: 50051

  - day: '02'
    replicas: 2
    version: v1

  - day: '03'
    replicas: 2
    version: v1

  - day: '04'
    replicas: 2
    version: v1

  - day: '05'
    replicas: 2
    version: v1

  - day: '06'
    replicas: 2
    version: v1

  - day: '07'
    replicas: 2
    version: v1

  - day: '08'
    replicas: 2
    version: v1

  - day: '09'
    replicas: 2
    version: v1

  - day: '10'
    replicas: 2
    version: v1

  - day: '11'
    replicas: 2
    version: v1

  - day: '12'
    replicas: 2
    version: v1

  - day: '13'
    replicas: 2
    version: v1

  - day: '14'
    replicas: 2
    version: v1

  - day: '15'
    replicas: 2
    version: v1

  - day: '16'
    replicas: 2
    version: v1

  - day: '17'
    replicas: 2
    version: v1

  - day: '18'
    replicas: 2
    version: v1

  - day: '19'
    replicas: 2
    version: v1

  - day: '20'
    replicas: 2
    version: v1

  - day: '21'
    replicas: 2
    version: v1

  - day: '22'
    replicas: 2
    version: v1

  - day: '23'
    replicas: 2
    version: v1

  - day: '24'
    replicas: 2
    version: v1

  - day: '25'
    replicas: 2
    version: v1
