{{- range .Values.days }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: aoc2024-day{{ .day }}
  labels:
    app: aoc2024
    day: "{{ .day }}"
    version: {{ .version | default "v1" }}

spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: aoc2024
      day: "{{ .day }}"
      version: {{ .version | default "v1" }}
  template:
    metadata:
      annotations:
        redeploy-timestamp: "{{ now | unixEpoch }}}"
      labels:
        app: aoc2024
        day: "{{ .day }}"
        version: {{ .version | default "v1" }}
    spec:
      containers:
        - name: aoc2024-day{{ .day }}
          image: aoc2024-day{{ .day }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .containerHttpPort | default 3000 }}
            - containerPort: {{ .containerGrpcPort | default 50051 }}

---
{{- end }}