{{- range .Values.days }}

apiVersion: v1
kind: Service
metadata:
  name: aoc2024-day{{ .day }}
  labels:
    app: aoc2024
    day: "{{ .day }}"
spec:
  type: ClusterIP
  selector:
    app: aoc2024
    day: "{{ .day }}"
  ports:
    - protocol: TCP
      port: {{ .serviceHttpPort | default 3000 }}
      targetPort: {{ .containerHttpPort | default 3000 }}
      name: http
    - protocol: TCP
      port: {{ .serviceGrpcPort | default 50051 }}
      targetPort: {{ .containerGrpcPort | default 50051 }}
      name: grpc

---
{{- end }}
