apiVersion: v1
kind: Secret
metadata:
  name: tls-certificate
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.cert.crtFile | b64enc }}
  tls.key: {{ .Files.Get .Values.cert.keyFile | b64enc }}
